version: '3'

services:
  spring-boot-app:
    container_name: spring-boot-app
    build: .
    ports:
      - 8081:8080
    restart: always
    networks:
      - my-network
#    volumes:
#      - ./:/data/spring-boot-app
#      - ~/.m2:/root/.m2

